name: pt_manager
services:
  database:
    image: postgres
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 512mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ptmanager_01
      POSTGRES_USER: ptmanager
      POSTGRES_DB: ptmanager